# Generated by Django 3.0.4 on 2020-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0003_auto_20200505_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='tribeIDToJoin',
            field=models.ManyToManyField(related_name='tribeIDToJoin', to='tribes.Tribe'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=172, primary_key=True, serialize=False),
        ),
    ]
