# Generated by Django 3.0.4 on 2020-05-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0004_auto_20200505_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=338, primary_key=True, serialize=False),
        ),
    ]
