# Generated by Django 3.0.4 on 2020-05-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0005_auto_20200505_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='houseID',
            field=models.IntegerField(default=709, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postID',
            field=models.IntegerField(default=669, primary_key=True, serialize=False),
        ),
    ]
